/*
 * Wrap the logic related to weather display.
 * It should be higher level logic then weather.
 */
#ifndef WEATHER_H
#define WEATHER_H

// Include Inkplate library to the sketch
#include "Inkplate.h"

// For Weather
#include "WeatherNetwork.h"

// Including icons generated by the py file
#include "icons.h"

// for the device. This could not be a class variable or function argument
// otherwise it will cause stack overflow
extern Inkplate display;

class Weather {
private:
    WeatherNetwork weatherNetwork;
    // Constant to determine when to full update
    const int fullRefresh = 60;

    // Draw the time MM-DD ddd hh:mm on top right
    void drawTime();
    // Draw QR code
    void drawQRCode();
    // Draw current weather
    void drawCurrent();
    // Draw temperature (C) for 48 hours
    void drawHourly();
    // Draw 8 daily weather
    void drawDaily();
    // draw for one day
    void drawOneDay(WeatherData &data, int index);
    // Human readable city name
    char city[128];
    char weatherFormat[7];
    // detailed weather data
    WeatherReport weatherReport;
public:
    // The main draw function
    void draw();
};
#endif
