/*
 * Wrap the logic related to weather display.
 * It should be higher level logic then weather.
 */
#ifndef WEATHER_H
#define WEATHER_H

// Include Inkplate library to the sketch
#include "Inkplate.h"

// For Weather
#include "WeatherNetwork.h"

// Including icons generated by the py file
#include "icons.h"

// from settings.h
extern char SECRET_CITY[128];
// for the device. This could not be a class variable or function argument
// otherwise it will cause stack overflow
extern Inkplate display;

class Weather {
private:
    WeatherNetwork weatherNetwork;
    // Constant to determine when to full update
    const int fullRefresh = 60;

    // Draw future weather
    void drawWeather();
    // Draw current weather
    void drawCurrent();
    // Draw temperature (C) for all days
    void drawTemps();
    // Draw city on bottom
    void drawCity();
    // Draw the time hh:mm on top right
    void drawTime();
public:
    // The main draw function
    void draw();
};
#endif
